name: Build and deploy action
on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2

      - name: docker build
        run: docker build -t elerbek1kamoloff/skypro1:$GITHUB_REF_NAME-$GITHUB_RUN_ID .

      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: docker push
        run: docker push elerbek1kamoloff/skypro1:$GITHUB_REF_NAME-$GITHUB_RUN_ID

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build_and_push
#    env:
#      POSTGRES_USER: ${{ secrets.DB_USER }}
#      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
#      SECRET_KEY: ${{ secrets.SECRET_KEY }}
#    steps:
#      - name: clone code
#        uses: actions/checkout@v2
#
#      - name: render configs
#        run: |-
#          mkdir deploy
#          cat docker-compose-ci.yaml | envsubst > deploy_ci/docker-compose.yaml
#          cat deploy/.env | envsubst > deploy_ci/.env
#
#      - name: copy files to server
#        uses: appleboy/scp-action@master
#        with:
#            host: ${{ secrets.SSH_HOST}}
#            username: ${{ secrets.SSH_USERNAME}}
#            password: ${{ secrets.SSH_PASSWORD}}
#            script: |
#              cd todolist
#              docker-compose down
#              docker-compose up -d