name: Build and deploy action
on:
  push:
    branches: ["master"]

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and Push Container
        run:
          docker build -t elerbek1kamoloff/skypro1:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
          docker push elerbek1kamoloff/skypro1:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    needs: build_and_push
    runs-on: ubuntu-20.04
    env:
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_NAME: ${{ secrets.DB_NAME }}
      DEBUG: ${{secrets.DEBUG}}

    steps:
      - name: clone code
        uses: actions/checkout@v3.5.2

      - name: Render configs
        run: |-
            mkdir deploy_ci
            cat docker-compose-ci.yaml | envsubst > deploy_ci/docker-compose.yaml
            cat deploy/.env | envsubst > deploy_ci/.env

      - name: copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.SSH_HOST}}
            username: ${{ secrets.SSH_USERNAME}}
            password: ${{ secrets.SSH_PASSWORD}}
            source: "deploy_ci/docker-compose.yaml, deploy_ci/.env"
            target: "deploy"
            strip_components: 1